#!/bin/sh
#
# Custom sources-final: Remove sources.list content
# Use /etc/apt/sources.list.d/ for package sources instead
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")

cat << EOF > $CHROOT/etc/apt/sources.list
# See /etc/apt/sources.list.d/ for package sources
EOF

exit 0
